# Packages included in ARM64 images by default
packages = [
  "grub-efi-arm64",
]
bootloaders = "grub-efi"

[additional_repositories.salt]
  architecture = "arm64"
  url = "https://packages.broadcom.com/artifactory/saltproject-deb"
  distribution = "stable"
  
[additional_repositories.zabbix]
  url = "https://repo.zabbix.com/zabbix/6.0/debian-arm64"
